### ISSUE TITLE
Can't read config.json: required key not provided @ data['arch']. Got None

### ISSUE THREAD

**Issue by mjkl-gh** [Tommatheussen/hassio-addons#2]
When trying to add your repo to my hassio installation I'm getting the following error: (and no plugins are added)

19-10-31 10:16:24 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/6fa18b9d/FreeDNS/config.json: required key not provided @ data['arch']. Got None
19-10-31 10:16:24 INFO (MainThread) [hassio.store] Load add-ons from store: 64 all - 0 new - 0 remove

I think something is wrong with your configured config.json file (did Home assistant add keys you are now missing?)

If I have time I will look into this and if i'm able to fix it I will open a PR

**Comment by Tommatheussen** [comment]
I actually don't use this addon anymore myself, so I'm not sure if it still is supported (probably not). I'll be archiving my repository, feel free to fork and attempt to get it back up and running
