### ISSUE TITLE
Not supported anymore?

### ISSUE THREAD

**Issue by Yonny24** [Tommatheussen/hassio-addons#3]
Hi,

This looks like a great alternative to duckdns.

Just installing it now.
Been a while since you made any updates - Is it still supported?

Update: Looks like it installed firefly not freedns- thought this was an addon from the repo list.

Thanks!

**Comment by Tommatheussen** [comment]
I actually don't use freeDNS anymore, as I got my own domain a while ago. I added firefly when it was not in the repository list of Home Assistant itself, that one shouldn't be needed anymore.

Seeing as I don't use these addons anymore myself, I will likely just archive them. Feel free to fork and improve if you want, I believe the freeDNS should still work with their current API, it might need some changes to work with the latest Home Assistant structure though.
